# Generated by Django 3.1.4 on 2020-12-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersManage', '0002_auto_20201208_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=9),
        ),
    ]
